# Generated by Django 4.0.5 on 2022-07-11 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_somemodel_delete_model1_delete_model2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SomeModel',
        ),
    ]
