# Generated by Django 4.0.5 on 2022-07-11 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_delete_somemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foo',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
    ]
